version = 0.1

[default.deploy.parameters]
stack_name = "job-finder"
resolve_s3 = true
s3_prefix = "job-finder"
region = "ap-northeast-2"
profile = "default"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
